# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mighty Kids Preschool
email: info@mightykidspreschool.com
description: >- # this means to ignore newlines until "baseurl:"
  Mighty Kids prepares preschoolers with Kidergarten readiness and STEM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: mightykidspreschool
github_username:  mightykidspreschool

# Build settings
source: src
destination: public
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  classes:
    output: true
    permalink: /classes/:path/
    layout: class
  gallery:
    output: true
    permalink: /gallery/:path/
    layout: gallery
phone: (425) 387-9343
hours: 9am - 1:30pm
email: info@mightykidspreschool.com
address: "1912 201st Pl SE #205"
city: Bothell
state: WA
zip: 98012
addressnote: "We are located inside of the Mighty Coders facility"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
