version: 2
jobs:
  dependencies-job:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package-lock.json"}}
            - v2-node-modules-
      - run:
          name: Update Bundler
          command: gem install bundler
      - run:
          name: Ruby dependencies
          command: bundle install

      - run:
          name: Node dependencies
          command: npm install firebase-tools

      - save_cache:
          paths:
            - /usr/local/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      - save_cache:
          paths:
            - /usr/local/lib/node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}


  build-job:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package-lock.json"}}
            - v2-node-modules-
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Get Checksum
          command: find public/ -type f -name "*" -exec md5sum {} + | awk '{print $1}' | sort | md5sum > checkfile
      - save_cache:
          key: public-cache-{{ checksum "checkfile" }}
          paths:
            - ./public/

  deploy-job:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package-lock.json"}}
            - v2-node-modules-
      - restore_cache:
          keys:
            - public-cache-
      - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
      version: 2
      -deploy:
        jobs:
          - dependencies-job
          - build-job:
              requires:
                - dependencies-job
          - deploy-job:
              requires:
                - build-job
              filters:
                branches:
                  only: master
